### ISSUE TITLE
Update halted use of plugin

### ISSUE THREAD

**Issue by lisapisapike** [JoryHogeveen/genesis-widget-column-classes#9]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Plugin Version:
  - WordPress Version:
  - Other plugins installed:
  - Theme:
  - Browser:

**Comment by JoryHogeveen** [comment]
Hi @lisapisapike,

Could you provide a bit more info?
Can't you see the classes on the widgets screen or aren't the classes rendered on the website?

Also, please answer the questions listed in the issue like WP version and the list of plugins.
Thanks! Jory

**Comment by lisapisapike** [comment]
Thank you so much for your reply as I know I really messed up my first posting in Github!


I am using WordPress v. 4.9.6


Using the Genesis Framework w/Business Pro Theme and your plugin is important for layout.


Just updated it and had some issues at first. But now the columns resolved on the website. I do still have this interesting error message within my plugin dash though.

Here is a screenshot.



Very Sincerely,


Lisa



Lisa Pike

Office Manager

Lightning Bolt, Inc.

3109 N. Cascade Ave., #202

Colorado Springs, CO  80907

PH: 719.473.5054 or 888.619.0724


________________________________

**Comment by JoryHogeveen** [comment]
Hi @lisapisapike,

Great to hear the layout etc. still works!
It seems the screenshot isn't working, are you replying by email or on GitHub?

You can also just copy/paste the error message you are seeing.

Thanks! Jory

**Comment by lisapisapike** [comment]
Here are the error messages Jory.


 Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 555


 Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 556


 Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 561


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 562


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 567


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 568


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 573


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 574


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 579


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 580


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 585


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 586


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 591


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 592


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 597


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 598


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 603


Notice: Use of undefined constant OCS_DOMAIN - assumed 'OCS_DOMAIN' in /Users/lisapike/Documents/Websites/www.lightningboltwebsite.dev.cc/wp-content/plugins/genesis-widget-column-classes/genesis-widget-column-classes.php on line 604




Very Sincerely,


Lisa



Lisa Pike

Office Manager

Lightning Bolt, Inc.

3109 N. Cascade Ave., #202

Colorado Springs, CO  80907

PH: 719.473.5054 or 888.619.0724


________________________________

**Comment by JoryHogeveen** [comment]
Hi @lisapisapike,

Thank you for this report! Issue is fixed in the latest version 1.2.4.1 which will be live in less than an hour!
Also, if you like the plugin, please consider leaving a nice review, it will help the plugin grow 🙂
https://wordpress.org/support/plugin/genesis-widget-column-classes/reviews/

_EDIT: Update is live! https://wordpress.org/plugins/genesis-widget-column-classes/_

Regards, Jory

**Comment by JoryHogeveen** [comment]
Thank you!!
https://wordpress.org/support/topic/super-plugin-with-stellar-support/
